// <auto-generated />
using System;
using ColorMemory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorMemory.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250331144331_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ColorMemory.Data.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArtworkId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("ColorMemory.Data.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IconId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("default");

                    b.Property<int>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ColorMemory.Data.PlayerArtwork", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<bool>("HasIt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("HintUsagePerStage")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("IncorrectPerStage")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ObtainedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TotalMistakesAndHints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("PlayerId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("PlayerArtworks");
                });

            modelBuilder.Entity("ColorMemory.Data.PlayerArtwork", b =>
                {
                    b.HasOne("ColorMemory.Data.Artwork", "Artwork")
                        .WithMany()
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColorMemory.Data.Player", "Player")
                        .WithMany("PlayerArtworks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ColorMemory.Data.Player", b =>
                {
                    b.Navigation("PlayerArtworks");
                });
#pragma warning restore 612, 618
        }
    }
}
